# -*- coding: utf-8 -*-
"""Generative_models.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18eSwL2yEdqwiHqs3hUIvR7czjBXARZEa
"""

with open('stuff1.txt', 'r', encoding="utf-8") as file:
  data = file.read().lower()
print(type(data))
print(data)

data = data.splitlines()

print(data)



#new_data = [ ]
for values in data:
  try:
    new_data.append(values.split('- ')[1])
  except:
    pass

print(new_data)

for stuff in new_data:

  with open('input.txt', mode='a', encoding='utf-8') as f:
    f.write(stuff)
    f.write('\n')
f.close()

! git clone https://github.com/sherjilozair/char-rnn-tensorflow.git

! cd 'char-rnn-tensorflow' && python train.py --init_from=save --num_epochs=100

! cd 'char-rnn-tensorflow' && python sample.py -n=3000 >>out.txt

! cp '/content/drive/My Drive/Programming Stuff/Colab Notebooks/Machine Learning/stuff1.txt' 'stuff1.txt'